-- seed_data.sql  |  Cole no SQL Editor do Supabase e clique Run
-- Gerado automaticamente de estudo-japones.html

-- Vocabulário (428 entradas)
INSERT INTO vocabulary (kanji, kana, portuguese, lesson, category) VALUES
  ('会う', 'あう', 'encontrar-se', 1, 'Verbos'),
  ('開く', 'あく', 'abrir (vi); funcionar', 1, 'Verbos'),
  ('遊ぶ', 'あそぶ', 'brincar', 1, 'Verbos'),
  ('ある', NULL, 'estar; existir; haver (inanimados)', 1, 'Verbos'),
  ('歩く', 'あるく', 'caminhar, andar', 1, 'Verbos'),
  ('行く', 'いく／ゆく', 'ir', 1, 'Verbos'),
  ('いる', NULL, 'estar; existir; haver (animados)', 1, 'Verbos'),
  ('歌う', 'うたう', 'cantar', 1, 'Verbos'),
  ('売る', 'うる', 'vender', 1, 'Verbos'),
  ('起きる', 'おきる', 'acordar; levantar-se', 1, 'Verbos'),
  ('置く', 'おく', 'deixar; pôr', 1, 'Verbos'),
  ('教える', 'おしえる', 'ensinar', 1, 'Verbos'),
  ('覚える', 'おぼえる', 'memorizar', 1, 'Verbos'),
  ('泳ぐ', 'およぐ', 'nadar', 1, 'Verbos'),
  ('終わる', 'おわる', 'terminar', 1, 'Verbos'),
  ('買う', 'かう', 'comprar', 1, 'Verbos'),
  ('帰る', 'かえる', 'voltar para casa', 1, 'Verbos'),
  ('書く', 'かく', 'escrever', 1, 'Verbos'),
  ('貸す', 'かす', 'emprestar', 1, 'Verbos'),
  ('借りる', 'かりる', 'tomar emprestado', 1, 'Verbos'),
  ('聞く', 'きく', 'ouvir; perguntar', 1, 'Verbos'),
  ('切る', 'きる', 'cortar', 1, 'Verbos'),
  ('着る', 'きる', 'vestir-se', 1, 'Verbos'),
  ('来る', 'くる', 'vir', 1, 'Verbos'),
  ('消す', 'けす', 'apagar; desligar', 1, 'Verbos'),
  ('結婚する', 'けっこんする', 'casar-se', 1, 'Verbos'),
  ('咲く', 'さく', 'florescer; desabrochar', 1, 'Verbos'),
  ('質問する', 'しつもんする', 'fazer perguntas', 1, 'Verbos'),
  ('死ぬ', 'しぬ', 'morrer', 1, 'Verbos'),
  ('閉まる', 'しまる', 'fechar (vi)', 1, 'Verbos'),
  ('知らせる', 'しらせる', 'avisar', 1, 'Verbos'),
  ('知る', 'しる', 'saber', 1, 'Verbos'),
  ('する', NULL, 'praticar; fazer', 1, 'Verbos'),
  ('立つ', 'たつ', 'levantar-se', 1, 'Verbos'),
  ('食べる', 'たべる', 'comer', 1, 'Verbos'),
  ('着く', 'つく', 'chegar', 1, 'Verbos'),
  ('飛ぶ', 'とぶ', 'voar', 1, 'Verbos'),
  ('止まる', 'とまる', 'parar (vi)', 1, 'Verbos'),
  ('取る', 'とる', 'pegar; tomar', 1, 'Verbos'),
  ('習う', 'ならう', 'aprender (com alguém)', 1, 'Verbos'),
  ('なる', NULL, 'tornar-se', 1, 'Verbos'),
  ('脱ぐ', 'ぬぐ', 'despir-se; tirar calçado', 1, 'Verbos'),
  ('寝る', 'ねる', 'dormir; deitar-se', 1, 'Verbos'),
  ('飲む', 'のむ', 'beber; tomar', 1, 'Verbos'),
  ('乗る', 'のる', 'embarcar; tomar condução', 1, 'Verbos'),
  ('走る', 'はしる', 'correr', 1, 'Verbos'),
  ('話す', 'はなす', 'conversar; falar', 1, 'Verbos'),
  ('勉強する', 'べんきょうする', 'estudar', 1, 'Verbos'),
  ('見る', 'みる', 'ver; assistir a', 1, 'Verbos'),
  ('休む', 'やすむ', 'descansar; faltar', 1, 'Verbos'),
  ('読む', 'よむ', 'ler', 1, 'Verbos'),
  ('練習する', 'れんしゅうする', 'treinar', 1, 'Verbos'),
  ('朝', 'あさ', 'manhã', 1, 'Substantivos'),
  ('明日', 'あした', 'amanhã', 1, 'Substantivos'),
  ('市場', 'いちば', 'feira', 1, 'Substantivos'),
  ('いとこ', NULL, 'primo, prima', 1, 'Substantivos'),
  ('いま', NULL, 'agora', 1, 'Substantivos'),
  ('歌', 'うた', 'canção; música', 1, 'Substantivos'),
  ('絵', 'え', 'desenho; figura', 1, 'Substantivos'),
  ('映画', 'えいが', 'cinema; filme', 1, 'Substantivos'),
  ('映画館', 'えいがかん', 'cinema (prédio)', 1, 'Substantivos'),
  ('おじ', NULL, 'tio (do falante)', 1, 'Substantivos'),
  ('音楽', 'おんがく', 'música', 1, 'Substantivos'),
  ('学生', 'がくせい', 'estudante', 1, 'Substantivos'),
  ('風', 'かぜ', 'vento', 1, 'Substantivos'),
  ('学校', 'がっこう', 'escola', 1, 'Substantivos'),
  ('ガラス', NULL, 'vidro', 1, 'Substantivos'),
  ('漢字', 'かんじ', 'ideograma; logograma', 1, 'Substantivos'),
  ('キッチン', NULL, 'cozinha', 1, 'Substantivos'),
  ('教会', 'きょうかい', 'igreja', 1, 'Substantivos'),
  ('教室', 'きょうしつ', 'sala de aula', 1, 'Substantivos'),
  ('果物屋', 'くだものや', 'casa de frutas', 1, 'Substantivos'),
  ('クラスメート', NULL, 'colega de classe', 1, 'Substantivos'),
  ('車', 'くるま', 'carro', 1, 'Substantivos'),
  ('公園', 'こうえん', 'parque; praça', 1, 'Substantivos'),
  ('ことば', NULL, 'palavra', 1, 'Substantivos'),
  ('子供', 'こども', 'criança; filho(a)', 1, 'Substantivos'),
  ('小鳥', 'ことり', 'passarinho', 1, 'Substantivos'),
  ('魚', 'さかな', 'peixe', 1, 'Substantivos'),
  ('サッカー', NULL, 'futebol', 1, 'Substantivos'),
  ('雑誌', 'ざっし', 'revista', 1, 'Substantivos'),
  ('時間', 'じかん', 'horário', 1, 'Substantivos'),
  ('辞書', 'じしょ', 'dicionário', 1, 'Substantivos'),
  ('授業', 'じゅぎょう', 'aula', 1, 'Substantivos'),
  ('ショッピングセンター', NULL, 'shopping center', 1, 'Substantivos'),
  ('新聞', 'しんぶん', 'jornal', 1, 'Substantivos'),
  ('生徒', 'せいと', 'aluno', 1, 'Substantivos'),
  ('先生', 'せんせい', 'professor (tratamento)', 1, 'Substantivos'),
  ('大学', 'だいがく', 'universidade; faculdade', 1, 'Substantivos'),
  ('近く', 'ちかく', 'perto', 1, 'Substantivos'),
  ('地図', 'ちず', 'mapa', 1, 'Substantivos'),
  ('机', 'つくえ', 'carteira; escrivaninha', 1, 'Substantivos'),
  ('電話', 'でんわ', 'telefone; telefonema', 1, 'Substantivos'),
  ('戸', 'と', 'porta', 1, 'Substantivos'),
  ('図書館', 'としょかん', 'biblioteca (prédio)', 1, 'Substantivos'),
  ('友達', 'ともだち', 'amigo(a)', 1, 'Substantivos'),
  ('鳥', 'とり', 'pássaro', 1, 'Substantivos'),
  ('部屋', 'へや', 'quarto', 1, 'Substantivos'),
  ('名前', 'なまえ', 'nome', 1, 'Substantivos'),
  ('日本', 'にほん', 'Japão', 1, 'Substantivos'),
  ('母', 'はは', '\u201cminha mãe\u201d (do falante)', 1, 'Substantivos'),
  ('左', 'ひだり', 'esquerda', 1, 'Substantivos'),
  ('ビール', NULL, 'cerveja', 1, 'Substantivos'),
  ('方々', 'ほうぼう', 'vários lugares', 1, 'Substantivos'),
  ('本', 'ほん', 'livro', 1, 'Substantivos'),
  ('毎日', 'まいにち', 'todos os dias', 1, 'Substantivos'),
  ('窓', 'まど', 'janela', 1, 'Substantivos'),
  ('マラソンランナー', NULL, 'corredor de maratona', 1, 'Substantivos'),
  ('右', 'みぎ', 'direita', 1, 'Substantivos'),
  ('店', 'みせ', 'loja', 1, 'Substantivos'),
  ('向こう', 'むこう', 'lá; outro lado', 1, 'Substantivos'),
  ('野菜', 'やさい', 'verdura', 1, 'Substantivos'),
  ('郵便局', 'ゆうびんきょく', 'correio', 1, 'Substantivos'),
  ('夜', 'よる', 'noite', 1, 'Substantivos'),
  ('来月', 'らいげつ', 'mês que vem', 1, 'Substantivos'),
  ('りんご', NULL, 'maçã', 1, 'Substantivos'),
  ('和食', 'わしょく', 'comida japonesa', 1, 'Substantivos'),
  ('小', 'こ', '(prefixo) diminutivo / algo pequeno', 1, 'Sufixos / Prefixo'),
  ('語', 'ご', '(sufixo) idioma: 日本語, 英語', 1, 'Sufixos / Prefixo'),
  ('さん', NULL, '(sufixo) respeito/consideração', 1, 'Sufixos / Prefixo'),
  ('屋', 'や', '(sufixo) comércio/profissional de…: 電気屋', 1, 'Sufixos / Prefixo'),
  ('青い空', 'あおいそら', 'céu azul', 1, 'Expressões'),
  ('雨が降る', 'あめがふる', 'chover', 1, 'Expressões'),
  ('絵をかく', 'えをかく', 'desenhar', 1, 'Expressões'),
  ('お天気のよい', 'おてんきのよい', 'tempo bom', 1, 'Expressões'),
  ('風が吹く', 'かぜがふく', 'ventar', 1, 'Expressões'),
  ('気づく', 'きづく', 'perceber', 1, 'Expressões'),
  ('電話をかける', 'でんわをかける', 'telefonar', 1, 'Expressões'),
  ('日が暮れる', 'ひがくれる', 'anoitecer', 1, 'Expressões'),
  ('持っている', 'もっている', 'possuir; ter', 1, 'Expressões'),
  ('方々に', 'ほうぼうに', 'para vários lugares', 1, 'Expressões'),
  ('集まる', 'あつまる', 'reunir-se', 2, 'Verbos'),
  ('入れる', 'いれる', 'colocar dentro; introduzir', 2, 'Verbos'),
  ('沈む', 'しずむ', 'pôr-se (sol/lua); afundar', 2, 'Verbos'),
  ('続く', 'つづく', 'continuar; estender-se', 2, 'Verbos'),
  ('のぼる', NULL, 'subir; nascer (sol/lua); aparecer', 2, 'Verbos'),
  ('家', 'いえ', 'casa', 2, 'Substantivos'),
  ('一年中', 'いちねんじゅう', 'ano inteiro', 2, 'Substantivos'),
  ('海', 'うみ', 'mar; oceano', 2, 'Substantivos'),
  ('会議', 'かいぎ', 'reunião', 2, 'Substantivos'),
  ('カレー', NULL, 'curry', 2, 'Substantivos'),
  ('今日', 'きょう', 'hoje', 2, 'Substantivos'),
  ('国', 'くに', 'país', 2, 'Substantivos'),
  ('ケイタイ', NULL, 'telefone celular', 2, 'Substantivos'),
  ('コーヒー', NULL, 'café', 2, 'Substantivos'),
  ('仕事', 'しごと', 'trabalho; serviço', 2, 'Substantivos'),
  ('自動車', 'じどうしゃ', 'automóvel', 2, 'Substantivos'),
  ('ジュース', NULL, 'suco', 2, 'Substantivos'),
  ('タイ', NULL, 'Tailândia', 2, 'Substantivos'),
  ('チーズ', NULL, 'queijo', 2, 'Substantivos'),
  ('月', 'つき', 'lua', 2, 'Substantivos'),
  ('電気', 'でんき', 'luz', 2, 'Substantivos'),
  ('となり', NULL, 'vizinho(a); vizinhança', 2, 'Substantivos'),
  ('ドレス', NULL, 'vestido', 2, 'Substantivos'),
  ('波', 'なみ', 'onda', 2, 'Substantivos'),
  ('ノルウェー', NULL, 'Noruega', 2, 'Substantivos'),
  ('パーティー', NULL, 'festa', 2, 'Substantivos'),
  ('日', 'ひ', 'sol', 2, 'Substantivos'),
  ('舟', 'ふね', 'barco', 2, 'Substantivos'),
  ('船', 'ふね', 'navio', 2, 'Substantivos'),
  ('フランス', NULL, 'França', 2, 'Substantivos'),
  ('ほたる', NULL, 'vagalume', 2, 'Substantivos'),
  ('水', 'みず', 'água', 2, 'Substantivos'),
  ('ヨーグルト', NULL, 'iogurte', 2, 'Substantivos'),
  ('ヨーロッパ', NULL, 'Europa', 2, 'Substantivos'),
  ('よそ', NULL, 'outro lugar; estrangeiro', 2, 'Substantivos'),
  ('読み方', 'よみかた', 'leitura', 2, 'Substantivos'),
  ('青い', 'あおい', 'azul', 2, 'Adjetivos 1'),
  ('赤い', 'あかい', 'vermelho', 2, 'Adjetivos 1'),
  ('明るい', 'あかるい', 'claro; iluminado', 2, 'Adjetivos 1'),
  ('新しい', 'あたらしい', 'novo', 2, 'Adjetivos 1'),
  ('暑い', 'あつい', 'quente (ar/ambiente)', 2, 'Adjetivos 1'),
  ('熱い', 'あつい', 'quente (bebida/comida)', 2, 'Adjetivos 1'),
  ('甘い', 'あまい', 'doce', 2, 'Adjetivos 1'),
  ('いい・よい', NULL, 'bom', 2, 'Adjetivos 1'),
  ('忙しい', 'いそがしい', 'ocupado, atarefado', 2, 'Adjetivos 1'),
  ('うるさい', NULL, 'barulhento', 2, 'Adjetivos 1'),
  ('おいしい', NULL, 'gostoso', 2, 'Adjetivos 1'),
  ('多い', 'おおい', 'numeroso; ter muito', 2, 'Adjetivos 1'),
  ('大きい', 'おおきい', 'grande', 2, 'Adjetivos 1'),
  ('おもしろい', NULL, 'interessante; engraçado', 2, 'Adjetivos 1'),
  ('悲しい', 'かなしい', 'triste', 2, 'Adjetivos 1'),
  ('かわいい', NULL, 'gracioso, bonitinho', 2, 'Adjetivos 1'),
  ('黄色い', 'きいろい', 'amarelo', 2, 'Adjetivos 1'),
  ('黒い', 'くろい', 'preto', 2, 'Adjetivos 1'),
  ('寒い', 'さむい', 'frio (clima)', 2, 'Adjetivos 1'),
  ('白い', 'しろい', 'branco', 2, 'Adjetivos 1'),
  ('涼しい', 'すずしい', 'fresco (ar/clima)', 2, 'Adjetivos 1'),
  ('すばらしい', NULL, 'maravilhoso', 2, 'Adjetivos 1'),
  ('狭い', 'せまい', 'estreito, apertado', 2, 'Adjetivos 1'),
  ('高い', 'たかい', 'alto; caro', 2, 'Adjetivos 1'),
  ('楽しい', 'たのしい', 'divertido', 2, 'Adjetivos 1'),
  ('茶色い', 'ちゃいろい', 'marrom', 2, 'Adjetivos 1'),
  ('冷たい', 'つめたい', 'gelado', 2, 'Adjetivos 1'),
  ('遠い', 'とおい', 'longe', 2, 'Adjetivos 1'),
  ('苦い', 'にがい', 'amargo', 2, 'Adjetivos 1'),
  ('広い', 'ひろい', 'amplo; largo', 2, 'Adjetivos 1'),
  ('古い', 'ふるい', 'velho; antigo', 2, 'Adjetivos 1'),
  ('難しい', 'むずかしい', 'difícil', 2, 'Adjetivos 1'),
  ('やさしい', NULL, 'fácil', 2, 'Adjetivos 1'),
  ('安い', 'やすい', 'barato', 2, 'Adjetivos 1'),
  ('若い', 'わかい', 'jovem', 2, 'Adjetivos 1'),
  ('いつも', NULL, 'sempre', 2, 'Advérbios'),
  ('少し', 'すこし', 'pouco', 2, 'Advérbios'),
  ('そんなに', NULL, 'tão; tanto (c/ negação: não tão)', 2, 'Advérbios'),
  ('いいえ', NULL, 'não', 2, 'Expressões'),
  ('ううん', NULL, 'não (informal)', 2, 'Expressões'),
  ('うん', NULL, 'sim (informal)', 2, 'Expressões'),
  ('行ってみたい', 'いってみたい', 'querer ir (experimentar)', 2, 'Expressões'),
  ('どんな', NULL, 'de que tipo', 2, 'Expressões'),
  ('はい', NULL, 'sim', 2, 'Expressões'),
  ('ゆれて', NULL, 'balançando', 2, 'Expressões'),
  ('～はどう？', NULL, 'que tal ~?', 2, 'Expressões'),
  ('でも', NULL, '(conj.) mas, embora, contudo', 2, 'Expressões'),
  ('洗う', 'あらう', 'lavar', 3, 'Verbos'),
  ('育てる', 'そだてる', 'cuidar, criar (vt)', 3, 'Verbos'),
  ('出かける', 'でかける', 'sair', 3, 'Verbos'),
  ('入る', 'はいる', 'entrar', 3, 'Verbos'),
  ('持っていく', 'もっていく', 'levar (objetos)', 3, 'Verbos'),
  ('犬', 'いぬ', 'cachorro', 3, 'Substantivos'),
  ('牛', 'うし', 'vaca, boi', 3, 'Substantivos'),
  ('うち', NULL, 'casa', 3, 'Substantivos'),
  ('馬', 'うま', 'cavalo', 3, 'Substantivos'),
  ('男の子', 'おとこのこ', 'menino', 3, 'Substantivos'),
  ('男の人', 'おとこのひと', 'homem', 3, 'Substantivos'),
  ('女の子', 'おんなのこ', 'menina', 3, 'Substantivos'),
  ('女の人', 'おんなのひと', 'mulher', 3, 'Substantivos'),
  ('買い物', 'かいもの', 'compras', 3, 'Substantivos'),
  ('学食', 'がくしょく', 'restaurante universitário', 3, 'Substantivos'),
  ('かさ', NULL, 'guarda-chuva', 3, 'Substantivos'),
  ('家族', 'かぞく', 'família', 3, 'Substantivos'),
  ('かばん', NULL, 'bolsa, mala', 3, 'Substantivos'),
  ('紙', 'かみ', 'papel', 3, 'Substantivos'),
  ('木', 'き', 'árvore', 3, 'Substantivos'),
  ('きのう', NULL, 'ontem', 3, 'Substantivos'),
  ('牛肉', 'ぎゅうにく', 'carne bovina', 3, 'Substantivos'),
  ('午後', 'ごご', 'p.m. (tarde)', 3, 'Substantivos'),
  ('午前', 'ごぜん', 'a.m. (manhã)', 3, 'Substantivos'),
  ('コップ', NULL, 'copo', 3, 'Substantivos'),
  ('ごはん', NULL, 'refeição; arroz cozido', 3, 'Substantivos'),
  ('コピー', NULL, 'cópia', 3, 'Substantivos'),
  ('シャツ', NULL, 'camisa', 3, 'Substantivos'),
  ('食事', 'しょくじ', 'refeição', 3, 'Substantivos'),
  ('スーパー', NULL, 'supermercado', 3, 'Substantivos'),
  ('大学生', 'だいがくせい', 'universitário', 3, 'Substantivos'),
  ('たまご', NULL, 'ovo', 3, 'Substantivos'),
  ('チョコレート', NULL, 'chocolate', 3, 'Substantivos'),
  ('テスト', NULL, 'prova', 3, 'Substantivos'),
  ('テキスト', NULL, 'texto', 3, 'Substantivos'),
  ('時計', 'とけい', 'relógio', 3, 'Substantivos'),
  ('中', 'なか', 'dentro', 3, 'Substantivos'),
  ('肉', 'にく', 'carne', 3, 'Substantivos'),
  ('庭', 'にわ', 'quintal', 3, 'Substantivos'),
  ('にんじん', NULL, 'cenoura', 3, 'Substantivos'),
  ('ノート', NULL, 'caderno', 3, 'Substantivos'),
  ('パパイヤ', NULL, 'mamão', 3, 'Substantivos'),
  ('パン', NULL, 'pão', 3, 'Substantivos'),
  ('日', 'ひ', 'dia', 3, 'Substantivos'),
  ('火', 'ひ', 'fogo', 3, 'Substantivos'),
  ('人', 'ひと', 'pessoa, gente', 3, 'Substantivos'),
  ('昼', 'ひる', 'tarde', 3, 'Substantivos'),
  ('びん', NULL, 'garrafa', 3, 'Substantivos'),
  ('ホテル', NULL, 'hotel', 3, 'Substantivos'),
  ('ボール', NULL, 'bola', 3, 'Substantivos'),
  ('ボールペン', NULL, 'caneta', 3, 'Substantivos'),
  ('みかん', NULL, 'laranja japonesa', 3, 'Substantivos'),
  ('ミネラルウオーター', NULL, 'água mineral', 3, 'Substantivos'),
  ('みんな', NULL, 'todos', 3, 'Substantivos'),
  ('山', 'やま', 'montanha', 3, 'Substantivos'),
  ('小さい', 'ちいさい', '(adj1) pequeno', 3, 'Adjetivos / Adnome'),
  ('茶色い', 'ちゃいろい', '(adj1) marrom', 3, 'Adjetivos / Adnome'),
  ('いろいろ', NULL, '(adj2) vários', 3, 'Adjetivos / Adnome'),
  ('大きな', 'おおきな', '(adnome) grande; imenso', 3, 'Adjetivos / Adnome'),
  ('小さな', 'ちいさな', '(adnome) pequeno', 3, 'Adjetivos / Adnome'),
  ('それから', NULL, '(conj.) depois', 3, 'Expressões'),
  ('いくつ', NULL, 'quantos', 3, 'Expressões'),
  ('行った', 'いった', 'fui', 3, 'Expressões'),
  ('買った', 'かった', 'comprei', 3, 'Expressões'),
  ('来た', 'きた', 'vieram', 3, 'Expressões'),
  ('した', NULL, 'fiz', 3, 'Expressões'),
  ('出かけた', 'でかけた', 'saímos', 3, 'Expressões'),
  ('みんなで', NULL, 'todos juntos', 3, 'Expressões'),
  ('もらった', NULL, 'ganhei', 3, 'Expressões'),
  ('～ごろ', NULL, '(sufixo) por volta de', 3, 'Expressões'),
  ('～前', 'まえ', '(sufixo) antes; para (horas)', 3, 'Expressões'),
  ('急ぐ', 'いそぐ', 'apressar-se', 4, 'Verbos'),
  ('泣く', 'なく', 'chorar', 4, 'Verbos'),
  ('始まる', 'はじまる', 'começar (vi); ter início', 4, 'Verbos'),
  ('流れる', 'ながれる', 'fluir; correr', 4, 'Verbos'),
  ('吠える', 'ほえる', 'latir; uivar', 4, 'Verbos'),
  ('分かる', 'わかる', 'entender; compreender', 4, 'Verbos'),
  ('住む', 'すむ', 'morar; habitar', 4, 'Verbos'),
  ('働く', 'はたらく', 'trabalhar', 4, 'Verbos'),
  ('受ける', 'うける', 'receber; fazer (exame)', 4, 'Verbos'),
  ('落ちる', 'おちる', 'cair; reprovar', 4, 'Verbos'),
  ('先週', 'せんしゅう', 'semana passada', 4, 'Substantivos'),
  ('先月', 'せんげつ', 'mês passado', 4, 'Substantivos'),
  ('去年', 'きょねん', 'ano passado', 4, 'Substantivos'),
  ('来年', 'らいねん', 'ano que vem', 4, 'Substantivos'),
  ('朝', 'あさ', 'manhã', 4, 'Substantivos'),
  ('昼', 'ひる', 'meio-dia; tarde', 4, 'Substantivos'),
  ('夕方', 'ゆうがた', 'tarde; entardecer', 4, 'Substantivos'),
  ('春', 'はる', 'primavera', 4, 'Substantivos'),
  ('夏', 'なつ', 'verão', 4, 'Substantivos'),
  ('秋', 'あき', 'outono', 4, 'Substantivos'),
  ('冬', 'ふゆ', 'inverno', 4, 'Substantivos'),
  ('写真', 'しゃしん', 'fotografia', 4, 'Substantivos'),
  ('問題', 'もんだい', 'problema; questão', 4, 'Substantivos'),
  ('レポート', NULL, 'relatório', 4, 'Substantivos'),
  ('メール', NULL, 'e-mail', 4, 'Substantivos'),
  ('空港', 'くうこう', 'aeroporto', 4, 'Substantivos'),
  ('体育館', 'たいいくかん', 'ginásio', 4, 'Substantivos'),
  ('教師', 'きょうし', 'professor (profissão)', 4, 'Substantivos'),
  ('エンジニア', NULL, 'engenheiro', 4, 'Substantivos'),
  ('会社', 'かいしゃ', 'empresa', 4, 'Substantivos'),
  ('～た', NULL, '(passado afirmativo simples)', 4, 'Expressões'),
  ('～なかった', NULL, '(passado negativo simples)', 4, 'Expressões'),
  ('～に なる', NULL, '(resultado) tornar-se ～', 4, 'Expressões'),
  ('時間がある', 'じかんがある', 'ter tempo; estar disponível', 4, 'Expressões'),
  ('六時に起きる', 'ろくじにおきる', 'acordar às 6 (に = tempo)', 4, 'Expressões'),
  ('学校に行く', 'がっこうにいく', 'ir à escola (に = destino)', 4, 'Expressões'),
  ('勝つ', 'かつ', 'vencer; ganhar', 5, 'Verbos'),
  ('探す', 'さがす', 'procurar; buscar', 5, 'Verbos'),
  ('調べる', 'しらべる', 'pesquisar; verificar', 5, 'Verbos'),
  ('考える', 'かんがえる', 'pensar; refletir', 5, 'Verbos'),
  ('始める', 'はじめる', 'começar (vt)', 5, 'Verbos'),
  ('続ける', 'つづける', 'continuar; prosseguir', 5, 'Verbos'),
  ('集まる', 'あつまる', 'reunir-se; juntar-se', 5, 'Verbos'),
  ('決める', 'きめる', 'decidir', 5, 'Verbos'),
  ('信じる', 'しんじる', 'acreditar; confiar', 5, 'Verbos'),
  ('負ける', 'まける', 'perder; ser derrotado', 5, 'Verbos'),
  ('安全', 'あんぜん', 'seguro', 5, 'Adjetivos な'),
  ('簡単', 'かんたん', 'simples; fácil', 5, 'Adjetivos な'),
  ('危険', 'きけん', 'perigoso', 5, 'Adjetivos な'),
  ('きれい', NULL, 'limpo; bonito', 5, 'Adjetivos な'),
  ('元気', 'げんき', 'saudável; animado', 5, 'Adjetivos な'),
  ('静か', 'しずか', 'silencioso; calmo', 5, 'Adjetivos な'),
  ('上手', 'じょうず', 'hábil; bom em algo (de outra pessoa)', 5, 'Adjetivos な'),
  ('親切', 'しんせつ', 'gentil; amável', 5, 'Adjetivos な'),
  ('好き', 'すき', 'gostar de (ser afeiçoado a)', 5, 'Adjetivos な'),
  ('得意', 'とくい', 'ponto forte; ser bom em (próprio)', 5, 'Adjetivos な'),
  ('苦手', 'にがて', 'ponto fraco; não ser bom em', 5, 'Adjetivos な'),
  ('にぎやか', NULL, 'animado; agitado (de lugar)', 5, 'Adjetivos な'),
  ('複雑', 'ふくざつ', 'complexo; complicado', 5, 'Adjetivos な'),
  ('不便', 'ふべん', 'inconveniente', 5, 'Adjetivos な'),
  ('下手', 'へた', 'ser ruim em algo', 5, 'Adjetivos な'),
  ('便利', 'べんり', 'prático; conveniente', 5, 'Adjetivos な'),
  ('有名', 'ゆうめい', 'famoso', 5, 'Adjetivos な'),
  ('必要', 'ひつよう', 'necessário', 5, 'Adjetivos な'),
  ('嫌い', 'きらい', 'detestar; não gostar de', 5, 'Adjetivos な'),
  ('丁寧', 'ていねい', 'educado; cuidadoso', 5, 'Adjetivos な'),
  ('素直', 'すなお', 'dócil; sincero', 5, 'Adjetivos な'),
  ('真剣', 'しんけん', 'sério; determinado', 5, 'Adjetivos な'),
  ('経済的', 'けいざいてき', 'econômico', 5, 'Adjetivos な'),
  ('実用的', 'じつようてき', 'prático; funcional', 5, 'Adjetivos な'),
  ('海', 'うみ', 'mar; oceano', 5, 'Substantivos'),
  ('山', 'やま', 'montanha', 5, 'Substantivos'),
  ('川', 'かわ', 'rio', 5, 'Substantivos'),
  ('地下鉄', 'ちかてつ', 'metrô', 5, 'Substantivos'),
  ('バス', NULL, 'ônibus', 5, 'Substantivos'),
  ('アパート', NULL, 'apartamento', 5, 'Substantivos'),
  ('仕事', 'しごと', 'trabalho', 5, 'Substantivos'),
  ('スポーツ', NULL, 'esporte', 5, 'Substantivos'),
  ('料理', 'りょうり', 'culinária; prato', 5, 'Substantivos'),
  ('得意 vs 上手', 'とくい vs じょうず', '得意 = próprio ponto forte · 上手 = habilidade observada em outra pessoa', 5, 'Expressões'),
  ('～だ / ～だった / ～ではない', NULL, '(cópula) predicado nominal: pres. afirm. · passado · negativo', 5, 'Expressões'),
  ('バスで行く', 'ばすでいく', 'ir de ônibus (で = meio)', 5, 'Expressões'),
  ('約束する', 'やくそくする', 'prometer; fazer uma combinação', 6, 'Verbos'),
  ('忘れる', 'わすれる', 'esquecer', 6, 'Verbos'),
  ('集める', 'あつめる', 'colecionar; reunir (vt)', 6, 'Verbos'),
  ('開ける', 'あける', 'abrir (vt)', 6, 'Verbos'),
  ('閉める', 'しめる', 'fechar (vt)', 6, 'Verbos'),
  ('片付ける', 'かたづける', 'arrumar; organizar', 6, 'Verbos'),
  ('助ける', 'たすける', 'ajudar; salvar', 6, 'Verbos'),
  ('見せる', 'みせる', 'mostrar', 6, 'Verbos'),
  ('送る', 'おくる', 'enviar; mandar', 6, 'Verbos'),
  ('迎える', 'むかえる', 'ir buscar; receber (alguém)', 6, 'Verbos'),
  ('細い', 'ほそい', 'fino; delgado', 6, 'Adjetivos い (novos)'),
  ('太い', 'ふとい', 'grosso', 6, 'Adjetivos い (novos)'),
  ('辛い', 'からい', 'picante; salgado', 6, 'Adjetivos い (novos)'),
  ('酸っぱい', 'すっぱい', 'azedo; ácido', 6, 'Adjetivos い (novos)'),
  ('眠い', 'ねむい', 'com sono; sonolento', 6, 'Adjetivos い (novos)'),
  ('痛い', 'いたい', 'doloroso; doer', 6, 'Adjetivos い (novos)'),
  ('うれしい', NULL, 'feliz; contente', 6, 'Adjetivos い (novos)'),
  ('かっこいい', NULL, 'bonito; estiloso', 6, 'Adjetivos い (novos)'),
  ('正しい', 'ただしい', 'correto', 6, 'Adjetivos い (novos)'),
  ('重い', 'おもい', 'pesado', 6, 'Adjetivos い (novos)'),
  ('軽い', 'かるい', 'leve', 6, 'Adjetivos い (novos)'),
  ('きたない', NULL, 'sujo; feio', 6, 'Adjetivos い (novos)'),
  ('～くて', NULL, '(て-form do adj-い) e; sendo ～', 6, 'Expressões'),
  ('～で', NULL, '(て-form do adj-な) e; sendo ～', 6, 'Expressões'),
  ('～くない / ～ではない', NULL, '(negação presente do adjetivo)', 6, 'Expressões'),
  ('～かった / だった', NULL, '(passado do adjetivo)', 6, 'Expressões'),
  ('～くなかった / ではなかった', NULL, '(passado negativo do adjetivo)', 6, 'Expressões'),
  ('きれいで、やさしい', NULL, '(adj-な) て-form: bonita e gentil', 6, 'Expressões'),
  ('旅行する', 'りょこうする', 'viajar', 7, 'Verbos'),
  ('散歩する', 'さんぽする', 'passear; caminhar', 7, 'Verbos'),
  ('料理する', 'りょうりする', 'cozinhar; preparar comida', 7, 'Verbos'),
  ('運動する', 'うんどうする', 'fazer exercício; praticar esporte', 7, 'Verbos'),
  ('連絡する', 'れんらくする', 'entrar em contato; avisar', 7, 'Verbos'),
  ('説明する', 'せつめいする', 'explicar', 7, 'Verbos'),
  ('準備する', 'じゅんびする', 'preparar; se preparar', 7, 'Verbos'),
  ('相談する', 'そうだんする', 'consultar; conversar sobre', 7, 'Verbos'),
  ('参加する', 'さんかする', 'participar', 7, 'Verbos'),
  ('確認する', 'かくにんする', 'confirmar; verificar', 7, 'Verbos'),
  ('～ます', NULL, '(presente/futuro polido — forma de dicionário → -ます)', 7, 'Forma ます'),
  ('～ました', NULL, '(passado polido)', 7, 'Forma ます'),
  ('～ません', NULL, '(negativo polido presente)', 7, 'Forma ます'),
  ('～ませんでした', NULL, '(negativo polido passado)', 7, 'Forma ます'),
  ('～ましょう', NULL, '(sugestão / vamos ～)', 7, 'Forma ます'),
  ('～ましょうか', NULL, '(oferta / posso ～?)', 7, 'Forma ます'),
  ('～たいです', NULL, '(desejo polido: gostaria de ～)', 7, 'Forma ます'),
  ('～に 行きます / 来ます', NULL, '(に = finalidade + verbo polido)', 7, 'Forma ます'),
  ('散歩', 'さんぽ', 'passeio (a pé)', 7, 'Substantivos'),
  ('旅行', 'りょこう', 'viagem', 7, 'Substantivos'),
  ('運動', 'うんどう', 'exercício físico', 7, 'Substantivos'),
  ('電話番号', 'でんわばんごう', 'número de telefone', 7, 'Substantivos'),
  ('毎朝', 'まいあさ', 'toda manhã', 7, 'Substantivos'),
  ('毎晩', 'まいばん', 'toda noite', 7, 'Substantivos'),
  ('週に一回', 'しゅうにいっかい', 'uma vez por semana', 7, 'Substantivos'),
  ('アルバイト', NULL, 'emprego temporário; bico', 7, 'Substantivos'),
  ('キャンパス', NULL, 'campus', 7, 'Substantivos'),
  ('授業料', 'じゅぎょうりょう', 'mensalidade escolar', 7, 'Substantivos'),
  ('よろしくお願いします', 'よろしくおねがいします', 'muito prazer; por favor (pedido formal)', 7, 'Expressões'),
  ('お元気ですか', 'おげんきですか', 'Como vai? (polido)', 7, 'Expressões'),
  ('ありがとうございます', NULL, 'obrigado(a) (polido formal)', 7, 'Expressões'),
  ('すみません', NULL, 'com licença; desculpe (polido)', 7, 'Expressões'),
  ('失礼します', 'しつれいします', 'com licença (ao entrar/sair de um lugar)', 7, 'Expressões');

-- Partículas
INSERT INTO particles (particle, romaji, lesson, role, description, example_jp, example_kana, example_pt) VALUES
  ('が', 'ga', 1, 'caso', 'indica o sujeito da oração', '子供が遊ぶ。', 'こどもがあそぶ', 'A criança brinca.'),
  ('が', 'ga', 3, 'conectiva', 'liga orações com sentido de \u201cmas\u201d', '安いが、おいしい。', 'やすいが、おいしい', 'É barato, mas gostoso.'),
  ('が', 'ga', 4, 'caso', 'forma o complemento de capacidade / possibilidade', '日本語が分かる。', 'にほんごがわかる', 'Entendo japonês.'),
  ('を', 'o', 1, 'caso', 'complemento do verbo transitivo direto (objeto)', '本を読む。', 'ほんをよむ', 'Leio um livro.'),
  ('の', 'no', 1, 'caso', '\u201cde / do / da\u201d — semelhante ao genitivo', '私の本', 'わたしのほん', 'meu livro'),
  ('で', 'de', 1, 'caso', 'indica o lugar onde a ação ocorre', '学校で勉強する。', 'がっこうでべんきょうする', 'Estudo na escola.'),
  ('で', 'de', 5, 'meio', 'meio / instrumento: \u201cpor\u201d, \u201cde\u201d', 'バスで行く。', 'バスでいく', 'Vou de ônibus.'),
  ('と', 'to', 1, 'caso', 'parceiro / companhia da ação do sujeito', '友達と話す。', 'ともだちとはなす', 'Converso com o amigo.'),
  ('と', 'to', 2, 'caso', 'enumeração aditiva \u201ce\u201d; parâmetro de comparação', '本とノート', 'ほんとノート', 'livro e caderno'),
  ('に', 'ni', 2, 'caso', 'local de existência ou colocação (\u201cem, sobre, dentro\u201d)', '庭に犬がいる。', 'にわにいぬがいる', 'Há um cachorro no quintal.'),
  ('に', 'ni', 4, 'caso', 'tempo da ação praticada pelo sujeito', '六時に起きる。', 'ろくじにおきる', 'Acordo às 6.'),
  ('に', 'ni', 4, 'caso', 'resultado de um processo (com なる etc.)', '教師になる。', 'きょうしになる', 'Torno-me professor.'),
  ('に', 'ni', 4, 'caso', 'destino, com verbos de deslocamento; いる・ある・住む sempre pedem に', '学校に行く。', 'がっこうにいく', 'Vou à escola.'),
  ('に', 'ni', 7, 'caso', 'finalidade da ação (com 行く/来る o verbo fica em れんようけい)', 'パンを買いに行く。', 'パンをかいにいく', 'Vou comprar pão.'),
  ('へ', 'e', 2, 'caso', 'direção do deslocamento: \u201cpara\u201d', '日本へ行く。', 'にほんへいく', 'Vou para o Japão.'),
  ('まで', 'made', 2, 'caso', 'ponto de chegada (espacial/temporal): \u201caté\u201d', '六時まで勉強する。', 'ろくじまでべんきょうする', 'Estudo até as 6.'),
  ('から', 'kara', 3, 'caso', 'ponto de partida (espacial/temporal): \u201ca partir de\u201d', '二時から勉強する。', 'にじからべんきょうする', 'Estudo a partir das 2.'),
  ('から', 'kara', 4, 'conectiva', 'causa (relação subjetiva): \u201ccomo / porque\u201d', '寒いから、セーターを着る。', 'さむいから…', 'Como está frio, visto um suéter.'),
  ('から', 'kara', 5, 'procedência', 'procedência: \u201cde\u201d', '外から人が来る。', 'そとからひとがくる', 'Vem gente de fora.'),
  ('は', 'wa', 2, 'adverbial', 'tópico do enunciado, ou ênfase / contraste', '私は学生だ。', 'わたしはがくせいだ', 'Eu sou estudante.'),
  ('も', 'mo', 2, 'adverbial', 'ênfase / contraste + acréscimo: \u201ctambém\u201d', '私も行く。', 'わたしもいく', 'Eu também vou.'),
  ('し', 'shi', 2, 'conectiva', 'interliga orações numa relação de adição', '安いし、おいしい。', 'やすいし…', 'É barato e ainda gostoso.'),
  ('ので', 'node', 4, 'conectiva', 'causa (relação objetiva): \u201ccomo / porque\u201d', '雨が降るので、行かない。', 'あめがふるので…', 'Como vai chover, não vou.'),
  ('だけ', 'dake', 4, 'restritiva', '\u201csomente / apenas\u201d', 'これだけ買う。', 'これだけかう', 'Compro só isto.'),
  ('か', 'ka', 5, 'final', 'partícula final de dúvida / pergunta', 'これは何ですか。', 'これはなんですか', 'O que é isto?'),
  ('など', 'nado', 5, 'caso', 'exemplificação: \u201cetc.\u201d', '本やノートなど', 'ほんやノートなど', 'livros, cadernos etc.'),
  ('より', 'yori', 5, 'comparação', '\u201cmais (do) que\u201d — recai sobre o termo comparado', 'バスより地下鉄が速い。', 'バスよりちかてつがはやい', 'O metrô é mais rápido que o ônibus.'),
  ('ながら', 'nagara', 7, 'conectiva', 'liga duas ações simultâneas do mesmo sujeito', 'テレビを見ながら勉強する。', 'テレビをみながら…', 'Estudo enquanto assisto à TV.'),
  ('ぞ', 'zo', 2, 'final', 'modalização: convencer / chamar a atenção do interlocutor', '行くぞ！', 'いくぞ', 'Vou, viu! / Vamos lá!'),
  ('な', 'na', 2, 'final', 'modalização: expressa emoção sobre o que se diz', 'きれいだな。', 'きれいだな', 'Que bonito!'),
  ('やら', 'yara', 2, 'modalização', 'indefinição / dúvida; ocorre com interrogativos', 'どこまで続くやら。', 'どこまでつづくやら', 'Até onde será que se estende…');